import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={e => {
          e.preventDefault()

          const formData = Object.fromEntries(
            new FormData(e.currentTarget).entries()
          )

          console.log(formData) 
        }}>
          <label>
            Question
            <input type="text" name="question" />
          </label>
          <br />
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  );
}
